apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configmap
  namespace: default
data:
  NODE_ENV: production
  DB_USER: postgres
  DB_HOST: countries-db
  DB_NAME: countries
  DB_PASSWORD: docker
  DB_PORT: '5432'
